name: ng_bulma_components
description: Bulma CSS AngularDart Components.
version: 0.1.0-alpha
#homepage: https://www.example.com
author: Alexander Haslam <alexander.haslam@reincarnadigital.com>

environment:
  sdk: '>=2.0.0-dev.32.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  bulma_sass: ^0.7.0

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.2
  build_test: ^0.10.1+1
  build_web_compilers: ^0.3.6
  sass_builder: ^1.2.0
  test: ^0.12.30
